

# # # # # #
# detect our machine type
# # # # # #

unameish="$(uname -s)"
machineType="NOTYET"
case "${unameish}" in
    Linux*)     machineType=Linux;;
    Darwin*)    machineType=Mac;;
    *)          machineType="UNKNOWN:${unameOut}"
esac
export machineType

# # # # # #
# now setup OS specific env vars
# # # # # #

if [[ "$machineType" == "Mac" ]]; then
	_homebrew=/opt/homebrew/bin/brew
fi

if [[ "$machineType" == "Linux" ]]; then
	_homebrew=/home/linuxbrew/.linuxbrew/bin/brew
fi

# always be central time for me
export TZ=CST6CDT


# # # # # #
# now pull in homebrew
# # # # # #

[ -e $_homebrew ] && eval "$($_homebrew shellenv zsh)"

# homebrew on linux can cause issues so let's be dirty here
skip_global_compinit=1
