eval "$(starship init zsh)"

# setup vi mode
# bindkey -v
export KEYTIMEOUT=1 # there's a delay for entering vim mode in zsh
source $(brew --prefix)/opt/zsh-vi-mode/share/zsh-vi-mode/zsh-vi-mode.plugin.zsh


alias ls="/bin/ls --color=auto -F"
alias ll="/bin/ls --color=auto -lF"
alias l="/bin/ls --color=auto -lrtF"
alias pyv="_pyv"

function mcd {
  dest=$1
  if [ -z $dest ]; then
    newdt=`date "+%Y%M%d"`
    dest="tmpd-${newdt}-${RANDOM}"
  fi
  mkdir -p $dest
  cd $dest
}

function _pyv {
  dest=$1
  if [ -z $dest ]; then
    dest="${HOME}/.pyvs/scratch"
  fi
  if [ ! -e $dest ]; then
    python3 -mvenv $dest
  fi
  source $dest/bin/activate
}

if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
  TERM=xterm-256color
else
  TERM=xterm-ghostty
fi
export TERM

